### ISSUE TITLE
打包后 3D 页面崩溃

### ISSUE THREAD

**Issue by Sun-ZhenXing** [zhuzichu520/PySide6-FluentUI-QML#12]
下载构建产物安装，3D 页面崩溃。原因是 `geometryloaders` / `renderers` 插件没有打包。

另外提供一个 Nuitka 打包的方案，理论上比 PyInstaller 更好（使用 C 代码转译，并编译 C 代码）。

```bat
python -m nuitka --standalone --mingw64 ^
    --plugin-enable=pyside6 ^
    --include-qt-plugins=sensible,styles,qml,geometryloaders,renderers ^
    --output-dir=dist ^
    --assume-yes-for-downloads ^
    main.py

@REM 复制 FluentUI QML
xcopy /Q /Y /S venv\Lib\site-packages\FluentUI\qml dist\main.dist\PySide6\qml
```

顺便问下作者，`FluPaneItem` 似乎有 `image` 选项，如何展示出来呢？还是说目前没有加入。

**Comment by zhuzichu520** [comment]
额，其实没什么用。像recentlyAdded、recentlyAdded、desc、image都是为了example加上的。。。这些后面都会删掉，因为看起来不是很灵活，后面会新增extra扩展字段，然后把example中的要用的数据弄一个一个object放到extra字段中
