### ISSUE TITLE
fluentuiplugin.dll 可以有mac或者linux的版本吗？

### ISSUE THREAD

**Issue by zaigie** [zhuzichu520/PySide6-FluentUI-QML#13]
又或者可以教一下编译动态链接库的方法？是通过C++版本生成吗？

**Comment by suterberg** [comment]
> 又或者可以教一下编译动态链接库的方法？是通过C++版本生成吗？

用qt creater 编译FluentUI 源码替换就可以了，QT本身是跨平台的
