### ISSUE TITLE
用 QtCreator 写 QML 的时候，预览窗口提示fluentuiplugin.dll：找不到指定的程序

### ISSUE THREAD

**Issue by chesterlyd** [zhuzichu520/PySide6-FluentUI-QML#19]
用 QtCreator 的 工具->外部->Qt Quick->Qt Quick2 Preview 预览QML 的时候提示fluentuiplugin.dll：找不到指定的程序

![image](https://github.com/zhuzichu520/PySide6-FluentUI-QML/assets/10460338/f7a0f154-24f1-4550-a8d7-103bc88f7c6f)
![image](https://github.com/zhuzichu520/PySide6-FluentUI-QML/assets/10460338/3e005fae-6b50-4017-8d29-d47abe778784)

**Comment by zhuzichu520** [comment]
这个预览工具不好用，相对资源还好，如果引入的是qrc资源，或者碰到需要在main函数中注册的组件，就会有问题~

**Comment by chesterlyd** [comment]
> 这个预览工具不好用，相对资源还好，如果引入的是qrc资源，或者碰到需要在main函数中注册的组件，就会有问题~

用qt creator 运行 example 代码的时候遇到了这个报错

![image](https://github.com/zhuzichu520/PySide6-FluentUI-QML/assets/10460338/ca1ecc41-bcc8-4fc3-9312-1dc9f0c0aaca)

**Comment by zhuzichu520** [comment]
嗯，QtCreator对python版的QML不太友好~忽略它
