### ISSUE TITLE
Example Run Error

### ISSUE THREAD

**Issue by EveryOrigin** [zhuzichu520/PySide6-FluentUI-QML#2]
我使用python setup.py install在，conda中一个命名为pyside6的环境中安装了此组件
pyside6                          6.6.0 
pyside6-addons             6.6.0
pyside6-essentials         6.6.0
pyside6-fluentui-qml    1.0.0 
python                           3.11.5 

在vscode中执行了:
- "Run pyside6-rcc"
- "Python: Current File"

然后产生了报错：

`(pyside6) c:\Users\yht\Desktop\Python-FluentUI\PySide6-FluentUI-QML> c: && cd c:\Users\yht\Desktop\Python-FluentUI\PySide6-FluentUI-QML && cmd /C "D:\torch\Anaconda3\envs\pyside6\python.exe c:\Users\yht\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 18877 -- example/main.py "
QCoreApplication::applicationFilePath: Please instantiate the QApplication object first
Application configuration file path -> <built-in method fileName of PySide6.QtCore.QSettings object at 0x000001B36F64D680>
FluentUI plugin dir ->D:\torch\Anaconda3\envs\pyside6\Lib\site-packages\pyside6_fluentui_qml-1.0.0-py3.11.egg\FluentUI/qml/FluentUI
['D:/torch/Anaconda3/envs/pyside6/Lib/site-packages/pyside6_fluentui_qml-1.0.0-py3.11.egg/FluentUI/qml', 'D:/torch/Anaconda3/envs/pyside6', 'qrc:/qt-project.org/imports', 'qrc:/qt/qml', 'D:/torch/Anaconda3/envs/pyside6/Lib/site-packages/PySide6/qml']
QQmlApplicationEngine failed to load component
qrc:/example/qml/App.qml:5:1: 无法加载库 D:\torch\Anaconda3\envs\pyside6\Lib\site-packages\pyside6_fluentui_qml-1.0.0-py3.11.egg\FluentUI\qml\FluentUI\fluentuiplugin.dll：找不到指定的程序

我很确定fluentuiplugin.dll在那个路径上存在

**Comment by zhuzichu520** [comment]
版本不一样，这个是Qt6.5.3版本，pyside最新版本是Qt6.6.0

**Comment by EveryOrigin** [comment]
> 版本不一样，这个是Qt6.5.3版本，pyside最新版本是Qt6.6.0

感谢你
