### ISSUE TITLE
pyside6 的组件库可以自己改一下功能吗

### ISSUE THREAD

**Issue by chesterlyd** [zhuzichu520/PySide6-FluentUI-QML#20]
pyside6 的组件库可以自己改一下功能吗？
我改了一下 安装好的FluentUI文件夹里的 qml 文件，但是没有生效

从 c++ 的库拉了代码下来改了一下，重新构建了提示
[Warning][App.qml:5][135740]:qrc:/example/qml/App.qml:5:1: 插件“D:/project/qt_test/PySide6-FluentUI-QML-main/test_model/lib/site-packages/FluentUI/qml/FluentUI/fluentuiplugin.dll”使用了不兼容的 Qt 库。(不能混合使用库的调试版本和发布版本。)

**Comment by zhuzichu520** [comment]
FluentUI中的qml没什么作用~删掉都没问题的。有用的是那个dll文件，需要源码重新编译
