### ISSUE TITLE
Nuitka打包后, 窗口大小异常

### ISSUE THREAD

**Issue by EveryOrigin** [zhuzichu520/PySide6-FluentUI-QML#21]
python版本3.11.5

包引用:

    PySide6                   6.6.1
    PySide6-Addons            6.6.1
    PySide6-Essentials        6.6.1
    PySide6-FluentUI-QML      1.6.6

主窗口:

    FluWindow {
        id: mainWindow
        width: 500
        height: 180
        fixSize: true
        launchMode: FluWindowType.Standard
        closeDestory: true
        backgroundColor: "#f9f9f9"
    }

在QtCreator中debug运行时, 窗口大小正常, fixSize生效(即禁用拖动缩放窗口大小)
但是有一个问题, 当我双击AppBar区域或者在此区域内拖动窗口时, 主窗口的height会突然减小20左右的数值

然后使用如下命令打包应用后运行:

    nuitka --mingw64 --standalone --enable-plugin=pyside6 --include-qt-plugins=all --show-memory --show-progress --follow-imports --follow-import-to=src --output-dir=o main.py

![image](https://github.com/zhuzichu520/PySide6-FluentUI-QML/assets/68151170/7b7ca6ea-312d-43fb-b097-2bd2a288532e)

很显然窗口没有遵循默认大小, 且在窗口边界区域可以拖动自由缩放大小..

**Comment by CZAsTc** [comment]
怎么解决的啊

**Comment by EveryOrigin** [comment]
> 怎么解决的啊

我这个纯纯是自己瓜皮, nuitka打包完之后我是手动把FluentUI的包丢进 打包出来的根目录下的, 结果丢错版本了
