### ISSUE TITLE
求解决qrc:/qt/qml/FluentUI/Controls/FluWindow.qml:5:1: module "org.wangwenx190.FramelessHelper" is not installed 方案

### ISSUE THREAD

**Issue by w-jt** [zhuzichu520/PySide6-FluentUI-QML#9]
import QtQuick
import QtQuick.Window
import FluentUI

FluWindow {
    width: 640
    height: 480
    visible: true
    title: qsTr("Hello World")

}

23:54:42: Starting C:\Program Files\Python311\python.exe -u main.py...
[Hook] attach 9560, C:\Program Files\Python311\python.exe
[Hook] detach 9560, C:\Program Files\Python311\python.exe
[Hook] detach 9560, C:\Program Files\Python311\python.exe
[Hook] detach 9560, C:\Program Files\Python311\python.exe
QQmlApplicationEngine failed to load component
file:///C:/Users/w/Documents/untitled1/main.qml:5:1: Type FluWindow unavailable
qrc:/qt/qml/FluentUI/Controls/FluWindow.qml:5:1: module "org.wangwenx190.FramelessHelper" is not installed
[Hook] detach 9560, C:\Program Files\Python311\python.exe
[Hook] detach 9560, C:\Program Files\Python311\python.exe
23:54:42: C:\Program Files\Python311\python.exe 退出，退出代码: -1
 {1 ?} {2?}

**Comment by zhuzichu520** [comment]
使用FluWindow前先初始化FluApp，代码详见https://github.com/zhuzichu520/PySide6-FluentUI-QML/blob/359a2acaa6d533f2e534dd26d1185fee27c5dcaa/example/resource/qml/App.qml#L41

**Comment by w-jt** [comment]
@zhuzichu520 
![image](https://github.com/zhuzichu520/PySide6-FluentUI-QML/assets/88316720/c9b667c8-27b0-4c3c-b8d6-cc59a42828ca)
QList(qrc:/qml/AppMainWindow.qml: No such file or directory)
为啥找不到文件？

**Comment by zhuzichu520** [comment]
要先将qrc文件用pyside6-rcc工具转换成py文件才能使用，然后在你的main.py中导入import resource.example_rc as rc

**Comment by zhuzichu520** [comment]
可以看下example中的https://github.com/zhuzichu520/PySide6-FluentUI-QML/blob/359a2acaa6d533f2e534dd26d1185fee27c5dcaa/example/main.py#L24

**Comment by w-jt** [comment]
已解决！！！谢谢 @zhuzichu520
